spring.application.name=sp04

server.servlet.context-path=/myApp

# datasource : DBMS, Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

# Mybatis Config
# settings => mybatis.configuration 
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
# typeAliases => mybatis.type-aliases-XXX
mybatis.type-aliases-package=com.yedam.app
# mappers => mybatis.mapper-locations
mybatis.mapper-locations=classpath:mapper/*.xml

# log 
logging.level.com.yedam.app=debug


# MultipartResolver Setting
spring.servlet.multipart.file-size-threshold=0B
spring.servlet.multipart.location=C:/temp
spring.servlet.multipart.max-file-size=1MB
spring.servlet.multipart.max-request-size=10MB


file.upload.path=D:/upload/

#spring.thymeleaf.prefix = 
#spring.thymeleaf.suffix = 





