# Spring Boot - DataSource Auto configuration Disable
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Log
logging.level.org.apache.ibatis=DEBUG
logging.level.com.yedam.app.mybatis=DEBUG
