spring.application.name=sp07

# datasource : DBMS, Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

#Mybatis
mybatis.configuration.map-underscore-to-camel-case=true
#null 강제로 넣는경우
mybatis.configuration.jdbc-type-for-null=VARCHAR    
mybatis.type-aliases-package=com.yedam.app
mybatis.mapper-locations=classpath:mapper/*.xml

#log 패키지 기준 mybatis 로그
logging.level.com.yedam.app=debug;
#dispatcher servlet
#logging.level.web=debug
#logging.level.sql=debug
##DB AOP 등 web과 관련 없는
#logging.level.root=debug